# Generated by Django 5.2.6 on 2025-12-27 08:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceteam',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='maintenance_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
