# Generated by Django 5.2.6 on 2025-12-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
