# Generated by Django 5.2.6 on 2025-12-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='maintenance_team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('scrap', 'Scrap')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='equipment',
            name='warranty_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
