# Generated by Django 5.2.6 on 2025-12-27 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_maintenance_team_equipment_purchase_date_and_more'),
        ('teams', '0002_maintenanceteam_members'),
    ]

    def create_teams_from_equipment(apps, schema_editor):
        Equipment = apps.get_model('equipment', 'Equipment')
        MaintenanceTeam = apps.get_model('teams', 'MaintenanceTeam')
        db_alias = schema_editor.connection.alias

        # Gather distinct non-empty maintenance_team string values from existing rows
        team_names = set()
        for eq in Equipment.objects.using(db_alias).all():
            val = getattr(eq, 'maintenance_team')
            if val:
                team_names.add(val)

        # Create MaintenanceTeam objects for each unique name and map to ids
        name_to_id = {}
        for name in team_names:
            team_obj, _ = MaintenanceTeam.objects.using(db_alias).get_or_create(name=name)
            name_to_id[name] = team_obj.id

        # Update equipment rows to point maintenance_team to the created team's id
        for eq in Equipment.objects.using(db_alias).all():
            val = getattr(eq, 'maintenance_team')
            if val and val in name_to_id:
                Equipment.objects.using(db_alias).filter(pk=eq.pk).update(maintenance_team=name_to_id[val])

    def noop(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(create_teams_from_equipment, noop),
        migrations.AlterField(
            model_name='equipment',
            name='maintenance_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.maintenanceteam'),
        ),
    ]
